---
hostname: 'centos'
domain: 'sympatica.io'
subdomain: 'masablog.pansymade.net'
username: 'dev'
mysshpublickey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDACL2fXAl5WRVY93gf5bwfdMRg1y/EefbUivKaUTNM523nowr5ZqBFTz53pAM4sqYs+4sXq+gTrT38hKvEdgwPYBv26yQRoNA3Ui3R0WkIDBMK6yy7aE8nsYt7hPjCBX/ZZyeUae9cXsUZw8jXsrYYVBM2rprKbvk9u74KjiRAVMSG08u8U7egmawbxz5T+00RN5Kv4wGe6PKykyuPuwsdw0Oy6zKGPdd0xWTi8/YeEwmbgWzsBK74H+REsUDbn8luflnF1CKgW5M16YV57cjTURFeTtPdIJpGVNMZ5YAb8yqFeDpLpXICIHrAgIV08DrRt9vFcZGqaAgFGqCiBnWZ NguyenTrung@Trung-MBP'
mailroot: 'patrick@sympatica.io'
monitalert: 'patrick@sympatica.io'
infopassword: 'ca3cffb9832d76976e55dd166f8b84926d2171b14debe962e624b6aac0836eb5'
masasampassword: '12867801203db4458032194913e86cf84c02933267b92378bca5d5d6100aaa4d'
mariadbrootpassword: 'QC1J56KNGQvk9Qc82nFa'
mackerelapikey: 'hLmRw4WQC1J56KNGQvk9Qc82nFa2h4j5m38XW3wCYMvG'
dbname: 'amazon'
dbpassword: 'xooShatie8'
docroot: '/home/html'
docrootblog: '/home/blog'
docrootppap: '/home/ppap'
docrootjekyll: '/home/jekyll'
docrootjekyll2: '/home/jekyll2'
docrootadminer: '/usr/share/webapps/adminer'
sendgridid: 'sg0bg3hc@kke.com'
sendgridpassword: 'masa3280'
