- name: install pip
  yum: name=python-pip state=present
  when: ansible_os_family == 'RedHat'
- name: Install libselinux-python.
  yum:
    name: libselinux-python
    state: present
  when: ansible_os_family == 'RedHat'
# - name: install mycli
#   pip: name=mycli
#   when: ansible_os_family == 'RedHat'